name: Cloud Workflow

on:
  workflow_dispatch:
    inputs:
        script:
          type: choice
          description: Script
          options: 
          - test.js

jobs:
  build:
    name: Run load test using the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run load test using actions tarball
        uses: grafana/k6-action@HEAD
        with:
          filename: ${{ github.event.inputs.script }}
          cloud: true
          token: ${{ secrets.K6_TOKEN }}
          flags: --vus 10 --duration 10s

