name: Main Workflow

on: workflow_dispatch

jobs:
  build:
    name: Run load test using the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run load test using actions tarball
        uses: grafana/k6-action@HEAD
        with:
          cloud: true
          token: ${{ secrets.K6_TOKEN }}
          flags: --vus 1 --duration 10s

